### ISSUE TITLE
new error message Error in fromJSON

### ISSUE THREAD

**Issue by ericpgreen** [prabhasp/formhub.R#7]
just started getting the following error:

```
Error in fromJSON(jsonfilename, encoding = "utf-8") : 
  unused argument (encoding = "utf-8")
```

when running:

```
mydf <- data.frame(formhubDownload("myform", myemail, pass = mypass))
```

code ran fine for months. any thoughts? did something change on the formhub end that would cause this?

**Comment by prabhasp** [comment]
Eric, the reason is because I upgraded formhub.R a bit. Could you run
sessionInfo() on your R console and provide me the output? Just wanted to
confirm what version of RJSONIO you have installed.

On Tue, Nov 26, 2013 at 10:51 AM, Eric Green notifications@github.comwrote:

> just started getting the following error:
> 
> Error in fromJSON(jsonfilename, encoding = "utf-8") :
>   unused argument (encoding = "utf-8")
> 
> when running:
> 
> mydf <- data.frame(formhubDownload("myform", myemail, pass = mypass))
> 
> code ran fine for months. any thoughts? did something change on the
> formhub end that would cause this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/prabhasp/formhub.R/issues/7
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by ericpgreen** [comment]
Thanks for the quick reply, Prabhas. RJSONIO_1.0-3

R version 3.0.2 (2013-09-25)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RVerboice_0.2    rjson_0.2.13     knitr_1.5        httr_0.2         formhub_0.0.3.8 
 [6] sp_1.0-14        doBy_4.5-9       MASS_7.3-29      multcomp_1.3-1   TH.data_1.0-2   
[11] survival_2.37-4  mvtnorm_0.9-9996 RCurl_1.95-4.1   bitops_1.0-6     stringr_0.6.2   
[16] RJSONIO_1.0-3    plyr_1.8         reshape2_1.2.2   lubridate_1.3.1 

loaded via a namespace (and not attached):
[1] digest_0.6.3    evaluate_0.5.1  formatR_0.10    grid_3.0.2      lattice_0.20-23
[6] memoise_0.1     sandwich_2.3-0  tools_3.0.2     zoo_1.7-10     

On November 26, 2013 at 11:14:45 AM, prabhasp (notifications@github.com) wrote:

Eric, the reason is because I upgraded formhub.R a bit. Could you run
sessionInfo() on your R console and provide me the output? Just wanted to
confirm what version of RJSONIO you have installed.

On Tue, Nov 26, 2013 at 10:51 AM, Eric Green notifications@github.comwrote:

> just started getting the following error:
> 
> Error in fromJSON(jsonfilename, encoding = "utf-8") :
> unused argument (encoding = "utf-8")
> 
> when running:
> 
> mydf <- data.frame(formhubDownload("myform", myemail, pass = mypass))
> 
> code ran fine for months. any thoughts? did something change on the
> formhub end that would cause this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/prabhasp/formhub.R/issues/7
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by prabhasp** [comment]
Eric, looks like you have the library rjson loaded, which also defines a
fromJSON. formhub.R uses the RJSONIO library instead; your problem is being
caused because rjson is also loaded up. I will make the call more specific
so that formhub uses RJSONIO's fromJSON. In the meantime, you can do
detach(package:rjson)
to unload the rjson package, and things should run fine. If they do, please
do let me know, and close the ticket :)

On Tue, Nov 26, 2013 at 11:17 AM, Eric Green notifications@github.comwrote:

> Thanks for the quick reply, Prabhas. RJSONIO_1.0-3
> 
> R version 3.0.2 (2013-09-25)
> Platform: x86_64-apple-darwin10.8.0 (64-bit)
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] splines   stats     graphics  grDevices utils     datasets  methods
> base
> 
> other attached packages:
>  [1] RVerboice_0.2    rjson_0.2.13     knitr_1.5        httr_0.2
> formhub_0.0.3.8
>  [6] sp_1.0-14        doBy_4.5-9       MASS_7.3-29      multcomp_1.3-1
> TH.data_1.0-2
> [11] survival_2.37-4  mvtnorm_0.9-9996 RCurl_1.95-4.1   bitops_1.0-6
> stringr_0.6.2
> [16] RJSONIO_1.0-3    plyr_1.8         reshape2_1.2.2   lubridate_1.3.1
> 
> loaded via a namespace (and not attached):
> [1] digest_0.6.3    evaluate_0.5.1  formatR_0.10    grid_3.0.2
>  lattice_0.20-23
> [6] memoise_0.1     sandwich_2.3-0  tools_3.0.2     zoo_1.7-10
> 
> On November 26, 2013 at 11:14:45 AM, prabhasp (notifications@github.com)
> wrote:
> 
> Eric, the reason is because I upgraded formhub.R a bit. Could you run
> sessionInfo() on your R console and provide me the output? Just wanted to
> confirm what version of RJSONIO you have installed.
> 
> On Tue, Nov 26, 2013 at 10:51 AM, Eric Green notifications@github.comwrote:
> 
> > just started getting the following error:
> > 
> > Error in fromJSON(jsonfilename, encoding = "utf-8") :
> > unused argument (encoding = "utf-8")
> > 
> > when running:
> > 
> > mydf <- data.frame(formhubDownload("myform", myemail, pass = mypass))
> > 
> > code ran fine for months. any thoughts? did something change on the
> > formhub end that would cause this?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/prabhasp/formhub.R/issues/7>
> > .
> 
> ## 
> 
> Prabhas Pokharel
> http://prabhasp.com
> US mobile: +1 347 948 7654
> twitter/skype/facebook/whatever: prabhasp
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/prabhasp/formhub.R/issues/7#issuecomment-29306043
> .

## 

Prabhas Pokharel
http://prabhasp.com
US mobile: +1 347 948 7654
twitter/skype/facebook/whatever: prabhasp

**Comment by ericpgreen** [comment]
Prabhas, you're right. Thanks for the suggestion. Detaching it works. Much appreciated.
